version: '3'

services:
  stateless-auth-db:
    container_name: stateless-auth-db
    image: postgres:latest
    environment:
      POSTGRES_DB: auth-db
      POSTGRESS_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - auth
    ports:
      - "5432:5432"
    
  stateless-auth-api:
    build: './stateless/stateless-auth-api'
    container_name: stateless-auth-api
    depends_on:
      - stateless-auth-db
    environment:
      - PORT=8080
      - DB_HOST=stateless-auth-db
      - DB_PORT=5432
      - DB_NAME=auth-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    networks:
      - auth
    ports:
      - "8080:8080"

  stateless-any-api:
    build: './stateless/stateless-any-api'
    container_name: stateless-any-api
    environment:
      - PORT=8081
    networks:
      - auth
    ports:
      - "8081:8081"
  
networks:
  auth:
    driver: bridge